import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import ScryptProviderClient from "../components/providers/ScryptProviderClient";
import TopNavbar from "@/components/shared/TopNavbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      {/* <ScryptProviderClient /> */}
      <body className={`${inter.className}w-full flex flex-col items-center`}>
        <TopNavbar />
        {children}
      </body>
    </html>
  );
}
